### PR TITLE
Dump the value of Tag::IDENTITY_CREDENTIAL_KEY.

### PR DESCRIPTION
**Pull request by AlexandreGonzalo**
I am using this tool to dump the attestation extensions generated by Keymint or Identity Credential and I think that it could be useful to dump the value of the Tag::IDENTITY_CREDENTIAL_KEY.

### CODE REVIEW

**Comment by eranmes** [comment]
@AlexandreGonzalo thanks for the contribution! can you please sign the CLA so we can merge this pull request?

**Comment by eranmes** [comment]
@AlexandreGonzalo checking - can you sign the CLA?

**Comment by AlexandreGonzalo** [comment]
Hi Eran,
The CLA was signed by my manager.
I am one of the owners of the group trustonic-android-services.
Maybe I missed something.
When I follw this link [https://cla.developers.google.com/github/rescan?pr=google%2Fandroid-key-attestation%2Fpull%2F9&key=%01%AD%3CDl%FA%2BYJ%FF%1D%95%8DVh%BE%D2%28%5C%8A%8E&expiry=2022-07-22](url), I have a 400 error page.

**Comment by AlexandreGonzalo** [comment]
It seems OK now.

**Pull request merged**
